// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package p_distribute

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DistStatus int32

const (
	DistStatus_DistWait    DistStatus = 0
	DistStatus_DistRun     DistStatus = 1
	DistStatus_DistFail    DistStatus = 2
	DistStatus_DistSuccess DistStatus = 3
)

var DistStatus_name = map[int32]string{
	0: "DistWait",
	1: "DistRun",
	2: "DistFail",
	3: "DistSuccess",
}

var DistStatus_value = map[string]int32{
	"DistWait":    0,
	"DistRun":     1,
	"DistFail":    2,
	"DistSuccess": 3,
}

func (x DistStatus) String() string {
	return proto.EnumName(DistStatus_name, int32(x))
}

func (DistStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

type ActionType int32

const (
	ActionType_ActWait    ActionType = 0
	ActionType_ActRun     ActionType = 1
	ActionType_ActFail    ActionType = 2
	ActionType_ActFailAll ActionType = 3
)

var ActionType_name = map[int32]string{
	0: "ActWait",
	1: "ActRun",
	2: "ActFail",
	3: "ActFailAll",
}

var ActionType_value = map[string]int32{
	"ActWait":    0,
	"ActRun":     1,
	"ActFail":    2,
	"ActFailAll": 3,
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}

func (ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

type FileDistInfo struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceFile           string     `protobuf:"bytes,2,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	StationName          string     `protobuf:"bytes,3,opt,name=station_name,json=stationName,proto3" json:"station_name,omitempty"`
	FileName             string     `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	TargetIp             string     `protobuf:"bytes,5,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	FtpUser              string     `protobuf:"bytes,6,opt,name=ftp_user,json=ftpUser,proto3" json:"ftp_user,omitempty"`
	FtpPass              string     `protobuf:"bytes,7,opt,name=ftp_pass,json=ftpPass,proto3" json:"ftp_pass,omitempty"`
	FtpPath              string     `protobuf:"bytes,8,opt,name=ftp_path,json=ftpPath,proto3" json:"ftp_path,omitempty"`
	FtpPort              int32      `protobuf:"varint,9,opt,name=ftp_port,json=ftpPort,proto3" json:"ftp_port,omitempty"`
	Progress             int32      `protobuf:"varint,10,opt,name=progress,proto3" json:"progress,omitempty"`
	Index                int32      `protobuf:"varint,11,opt,name=index,proto3" json:"index,omitempty"`
	Status               DistStatus `protobuf:"varint,12,opt,name=status,proto3,enum=p_distribute.DistStatus" json:"status,omitempty"`
	Eid                  string     `protobuf:"bytes,13,opt,name=eid,proto3" json:"eid,omitempty"`
	Time                 int32      `protobuf:"varint,14,opt,name=time,proto3" json:"time,omitempty"`
	AlbumName            string     `protobuf:"bytes,15,opt,name=album_name,json=albumName,proto3" json:"album_name,omitempty"`
	ErrMsg               string     `protobuf:"bytes,16,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Attr                 string     `protobuf:"bytes,17,opt,name=attr,proto3" json:"attr,omitempty"`
	Name                 string     `protobuf:"bytes,18,opt,name=name,proto3" json:"name,omitempty"`
	FileSize             uint64     `protobuf:"varint,19,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Speed                string     `protobuf:"bytes,20,opt,name=speed,proto3" json:"speed,omitempty"`
	FileSizeh            string     `protobuf:"bytes,21,opt,name=file_sizeh,json=fileSizeh,proto3" json:"file_sizeh,omitempty"`
	DistType             int32      `protobuf:"varint,22,opt,name=dist_type,json=distType,proto3" json:"dist_type,omitempty"`
	DistSubType          int64      `protobuf:"varint,23,opt,name=dist_sub_type,json=distSubType,proto3" json:"dist_sub_type,omitempty"`
	LocalIp              string     `protobuf:"bytes,24,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FileDistInfo) Reset()         { *m = FileDistInfo{} }
func (m *FileDistInfo) String() string { return proto.CompactTextString(m) }
func (*FileDistInfo) ProtoMessage()    {}
func (*FileDistInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *FileDistInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDistInfo.Unmarshal(m, b)
}
func (m *FileDistInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDistInfo.Marshal(b, m, deterministic)
}
func (m *FileDistInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDistInfo.Merge(m, src)
}
func (m *FileDistInfo) XXX_Size() int {
	return xxx_messageInfo_FileDistInfo.Size(m)
}
func (m *FileDistInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDistInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileDistInfo proto.InternalMessageInfo

func (m *FileDistInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FileDistInfo) GetSourceFile() string {
	if m != nil {
		return m.SourceFile
	}
	return ""
}

func (m *FileDistInfo) GetStationName() string {
	if m != nil {
		return m.StationName
	}
	return ""
}

func (m *FileDistInfo) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileDistInfo) GetTargetIp() string {
	if m != nil {
		return m.TargetIp
	}
	return ""
}

func (m *FileDistInfo) GetFtpUser() string {
	if m != nil {
		return m.FtpUser
	}
	return ""
}

func (m *FileDistInfo) GetFtpPass() string {
	if m != nil {
		return m.FtpPass
	}
	return ""
}

func (m *FileDistInfo) GetFtpPath() string {
	if m != nil {
		return m.FtpPath
	}
	return ""
}

func (m *FileDistInfo) GetFtpPort() int32 {
	if m != nil {
		return m.FtpPort
	}
	return 0
}

func (m *FileDistInfo) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *FileDistInfo) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *FileDistInfo) GetStatus() DistStatus {
	if m != nil {
		return m.Status
	}
	return DistStatus_DistWait
}

func (m *FileDistInfo) GetEid() string {
	if m != nil {
		return m.Eid
	}
	return ""
}

func (m *FileDistInfo) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *FileDistInfo) GetAlbumName() string {
	if m != nil {
		return m.AlbumName
	}
	return ""
}

func (m *FileDistInfo) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *FileDistInfo) GetAttr() string {
	if m != nil {
		return m.Attr
	}
	return ""
}

func (m *FileDistInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileDistInfo) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *FileDistInfo) GetSpeed() string {
	if m != nil {
		return m.Speed
	}
	return ""
}

func (m *FileDistInfo) GetFileSizeh() string {
	if m != nil {
		return m.FileSizeh
	}
	return ""
}

func (m *FileDistInfo) GetDistType() int32 {
	if m != nil {
		return m.DistType
	}
	return 0
}

func (m *FileDistInfo) GetDistSubType() int64 {
	if m != nil {
		return m.DistSubType
	}
	return 0
}

func (m *FileDistInfo) GetLocalIp() string {
	if m != nil {
		return m.LocalIp
	}
	return ""
}

type FileDistList struct {
	Items                []*FileDistInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total                int32           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FileDistList) Reset()         { *m = FileDistList{} }
func (m *FileDistList) String() string { return proto.CompactTextString(m) }
func (*FileDistList) ProtoMessage()    {}
func (*FileDistList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *FileDistList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDistList.Unmarshal(m, b)
}
func (m *FileDistList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDistList.Marshal(b, m, deterministic)
}
func (m *FileDistList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDistList.Merge(m, src)
}
func (m *FileDistList) XXX_Size() int {
	return xxx_messageInfo_FileDistList.Size(m)
}
func (m *FileDistList) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDistList.DiscardUnknown(m)
}

var xxx_messageInfo_FileDistList proto.InternalMessageInfo

func (m *FileDistList) GetItems() []*FileDistInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *FileDistList) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ActionInfo struct {
	ActType              ActionType    `protobuf:"varint,1,opt,name=act_type,json=actType,proto3,enum=p_distribute.ActionType" json:"act_type,omitempty"`
	FileInfo             *FileDistInfo `protobuf:"bytes,2,opt,name=file_info,json=fileInfo,proto3" json:"file_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ActionInfo) Reset()         { *m = ActionInfo{} }
func (m *ActionInfo) String() string { return proto.CompactTextString(m) }
func (*ActionInfo) ProtoMessage()    {}
func (*ActionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *ActionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionInfo.Unmarshal(m, b)
}
func (m *ActionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionInfo.Marshal(b, m, deterministic)
}
func (m *ActionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionInfo.Merge(m, src)
}
func (m *ActionInfo) XXX_Size() int {
	return xxx_messageInfo_ActionInfo.Size(m)
}
func (m *ActionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ActionInfo proto.InternalMessageInfo

func (m *ActionInfo) GetActType() ActionType {
	if m != nil {
		return m.ActType
	}
	return ActionType_ActWait
}

func (m *ActionInfo) GetFileInfo() *FileDistInfo {
	if m != nil {
		return m.FileInfo
	}
	return nil
}

type PageInfo struct {
	PageSize             int32      `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Totle                int32      `protobuf:"varint,2,opt,name=totle,proto3" json:"totle,omitempty"`
	Page                 int32      `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Status               DistStatus `protobuf:"varint,4,opt,name=status,proto3,enum=p_distribute.DistStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{3}
}

func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (m *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(m, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PageInfo) GetTotle() int32 {
	if m != nil {
		return m.Totle
	}
	return 0
}

func (m *PageInfo) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageInfo) GetStatus() DistStatus {
	if m != nil {
		return m.Status
	}
	return DistStatus_DistWait
}

type DistResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistResponse) Reset()         { *m = DistResponse{} }
func (m *DistResponse) String() string { return proto.CompactTextString(m) }
func (*DistResponse) ProtoMessage()    {}
func (*DistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{4}
}

func (m *DistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistResponse.Unmarshal(m, b)
}
func (m *DistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistResponse.Marshal(b, m, deterministic)
}
func (m *DistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistResponse.Merge(m, src)
}
func (m *DistResponse) XXX_Size() int {
	return xxx_messageInfo_DistResponse.Size(m)
}
func (m *DistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DistResponse proto.InternalMessageInfo

func (m *DistResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DistResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("p_distribute.DistStatus", DistStatus_name, DistStatus_value)
	proto.RegisterEnum("p_distribute.ActionType", ActionType_name, ActionType_value)
	proto.RegisterType((*FileDistInfo)(nil), "p_distribute.FileDistInfo")
	proto.RegisterType((*FileDistList)(nil), "p_distribute.FileDistList")
	proto.RegisterType((*ActionInfo)(nil), "p_distribute.ActionInfo")
	proto.RegisterType((*PageInfo)(nil), "p_distribute.PageInfo")
	proto.RegisterType((*DistResponse)(nil), "p_distribute.DistResponse")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcf, 0x6e, 0xfa, 0x46,
	0x10, 0xae, 0x01, 0x83, 0x19, 0x13, 0x7e, 0x74, 0xfb, 0x6b, 0xb2, 0xa1, 0xaa, 0x4a, 0x39, 0xa1,
	0x1c, 0xa2, 0x28, 0xa9, 0xd4, 0x53, 0x2b, 0x11, 0xa1, 0x44, 0x48, 0x4d, 0x15, 0x99, 0xfe, 0x39,
	0xa2, 0xc5, 0x1e, 0x60, 0x25, 0x63, 0x5b, 0xbb, 0x6b, 0xa9, 0xc9, 0xb5, 0x2f, 0xd2, 0xf7, 0xea,
	0xcb, 0x54, 0x3b, 0x6b, 0x03, 0x51, 0x53, 0x5a, 0xf5, 0x82, 0x66, 0xe6, 0x9b, 0x19, 0x66, 0xbe,
	0xf9, 0x16, 0x20, 0x2c, 0x54, 0x6e, 0xf2, 0x6b, 0xfa, 0x64, 0xbd, 0x62, 0x99, 0x48, 0x6d, 0x94,
	0x5c, 0x95, 0x06, 0xc7, 0x7f, 0xf8, 0xd0, 0x7b, 0x90, 0x29, 0xce, 0xa4, 0x36, 0xf3, 0x6c, 0x9d,
	0xb3, 0x3e, 0x34, 0x64, 0xc2, 0xbd, 0x91, 0x37, 0xe9, 0x46, 0x0d, 0x99, 0xb0, 0xaf, 0x20, 0xd4,
	0x79, 0xa9, 0x62, 0x5c, 0xae, 0x65, 0x8a, 0xbc, 0x41, 0x00, 0xb8, 0x90, 0x2d, 0x64, 0x5f, 0x43,
	0x4f, 0x1b, 0x61, 0x64, 0x9e, 0x2d, 0x33, 0xb1, 0x43, 0xde, 0xa4, 0x8c, 0xb0, 0x8a, 0xfd, 0x28,
	0x76, 0xc8, 0xbe, 0x80, 0xae, 0x2d, 0x76, 0x78, 0x8b, 0xf0, 0xc0, 0x06, 0x6a, 0xd0, 0x08, 0xb5,
	0x41, 0xb3, 0x94, 0x05, 0xf7, 0x1d, 0xe8, 0x02, 0xf3, 0x82, 0x5d, 0x42, 0xb0, 0x36, 0xc5, 0xb2,
	0xd4, 0xa8, 0x78, 0x9b, 0xb0, 0xce, 0xda, 0x14, 0x3f, 0x6b, 0x54, 0x35, 0x54, 0x08, 0xad, 0x79,
	0x67, 0x0f, 0x3d, 0x0b, 0xad, 0x0f, 0x90, 0xd9, 0xf2, 0xe0, 0x08, 0x32, 0xdb, 0x3d, 0x94, 0x2b,
	0xc3, 0xbb, 0x23, 0x6f, 0xe2, 0x3b, 0x28, 0x57, 0x86, 0x0d, 0x21, 0x28, 0x54, 0xbe, 0x51, 0xa8,
	0x35, 0x07, 0x82, 0xf6, 0x3e, 0xfb, 0x08, 0xbe, 0xcc, 0x12, 0xfc, 0x8d, 0x87, 0x04, 0x38, 0x87,
	0xdd, 0x40, 0xdb, 0xae, 0x59, 0x6a, 0xde, 0x1b, 0x79, 0x93, 0xfe, 0x2d, 0xbf, 0x3e, 0xe6, 0xf6,
	0xda, 0x72, 0xba, 0x20, 0x3c, 0xaa, 0xf2, 0xd8, 0x00, 0x9a, 0x28, 0x13, 0x7e, 0x46, 0x43, 0x59,
	0x93, 0x31, 0x68, 0x19, 0xb9, 0x43, 0xde, 0xa7, 0xc6, 0x64, 0xb3, 0x2f, 0x01, 0x44, 0xba, 0x2a,
	0x77, 0x8e, 0xb0, 0x0f, 0x94, 0xdc, 0xa5, 0x08, 0x31, 0x76, 0x01, 0x1d, 0x54, 0x6a, 0xb9, 0xd3,
	0x1b, 0x3e, 0x20, 0xac, 0x8d, 0x4a, 0x3d, 0xe9, 0x8d, 0xed, 0x25, 0x8c, 0x51, 0xfc, 0x53, 0x8a,
	0x92, 0x6d, 0x63, 0xd4, 0x85, 0xb9, 0x58, 0x76, 0x7c, 0x0f, 0x2d, 0x5f, 0x91, 0x7f, 0x36, 0xf2,
	0x26, 0x2d, 0x77, 0x8f, 0x85, 0x7c, 0x45, 0xbb, 0xaa, 0x2e, 0x10, 0x13, 0xfe, 0x91, 0x2a, 0x9c,
	0x63, 0x47, 0xda, 0x97, 0x6c, 0xf9, 0xe7, 0x6e, 0xa4, 0xba, 0x66, 0x6b, 0x3b, 0xda, 0xc5, 0x97,
	0xe6, 0xa5, 0x40, 0x7e, 0xee, 0xc8, 0xb3, 0x81, 0x9f, 0x5e, 0x0a, 0x64, 0x63, 0x38, 0x23, 0x50,
	0x97, 0x2b, 0x97, 0x70, 0x41, 0x09, 0xa1, 0x0d, 0x2e, 0xca, 0x15, 0xe5, 0x5c, 0x42, 0x90, 0xe6,
	0xb1, 0x48, 0xad, 0x08, 0xb8, 0x3b, 0x19, 0xf9, 0xf3, 0x62, 0xfc, 0xcb, 0x41, 0xa1, 0x3f, 0x48,
	0x6d, 0xd8, 0x0d, 0xf8, 0xd2, 0xe0, 0x4e, 0x73, 0x6f, 0xd4, 0x9c, 0x84, 0xb7, 0xc3, 0xb7, 0xa4,
	0x1f, 0x8b, 0x39, 0x72, 0x89, 0x76, 0x25, 0x93, 0x1b, 0x91, 0x92, 0x7a, 0xfd, 0xc8, 0x39, 0xe3,
	0x57, 0x80, 0x69, 0x6c, 0x35, 0x4a, 0xba, 0xbf, 0x83, 0x40, 0xc4, 0xd5, 0x02, 0xde, 0x7b, 0xd7,
	0x74, 0xb9, 0x76, 0xd8, 0xa8, 0x23, 0x62, 0xb7, 0xd9, 0xb7, 0x15, 0x91, 0x32, 0x5b, 0xe7, 0xd4,
	0xfc, 0xf4, 0x38, 0x44, 0xb2, 0xb5, 0xc6, 0xbf, 0x7b, 0x10, 0x3c, 0x8b, 0x0d, 0x39, 0x96, 0xbc,
	0x42, 0x6c, 0xaa, 0x73, 0x78, 0x95, 0xf2, 0xc4, 0x66, 0x7f, 0x0e, 0x93, 0x9b, 0xea, 0xe5, 0xb9,
	0xd9, 0x53, 0xb4, 0x57, 0xb5, 0x19, 0xf4, 0xd8, 0xfc, 0x88, 0xec, 0x23, 0x35, 0xb6, 0xfe, 0x9b,
	0x1a, 0xc7, 0xdf, 0x40, 0xcf, 0x46, 0x23, 0xd4, 0x45, 0x9e, 0x69, 0xea, 0x1a, 0xe7, 0x49, 0x3d,
	0x03, 0xd9, 0x56, 0xb1, 0x56, 0x68, 0xee, 0xdd, 0x5b, 0xf3, 0xea, 0x01, 0xe0, 0xd0, 0x8b, 0xf5,
	0x20, 0xb0, 0xde, 0xaf, 0x42, 0x9a, 0xc1, 0x27, 0x2c, 0x84, 0x0e, 0x75, 0x2c, 0xb3, 0x81, 0x57,
	0x43, 0x0f, 0x42, 0xa6, 0x83, 0x06, 0xfb, 0x00, 0x21, 0x95, 0x95, 0x71, 0x8c, 0x5a, 0x0f, 0x9a,
	0x57, 0xf7, 0x35, 0xff, 0x44, 0x65, 0x08, 0x9d, 0x69, 0x5c, 0xb7, 0x01, 0x68, 0x4f, 0xe3, 0xaa,
	0x8b, 0x03, 0xaa, 0x26, 0x7d, 0xaa, 0xb1, 0xce, 0x34, 0x4d, 0x07, 0xcd, 0xdb, 0x3f, 0x1b, 0xd0,
	0x79, 0x42, 0xad, 0xed, 0xfe, 0x8f, 0x70, 0x36, 0x4d, 0x92, 0xd9, 0x7e, 0x63, 0xf6, 0x0f, 0xa7,
	0xb0, 0x22, 0x1a, 0x0e, 0xff, 0x4e, 0xce, 0x9e, 0x86, 0x19, 0xf4, 0x1f, 0xd1, 0x1c, 0x1a, 0x69,
	0x76, 0xfe, 0x36, 0xbb, 0xbe, 0xdc, 0xf0, 0xc4, 0x37, 0xb0, 0x7b, 0x08, 0x16, 0x68, 0xe6, 0xf4,
	0x43, 0x71, 0x42, 0x14, 0x27, 0x27, 0xf9, 0x0e, 0xfc, 0x08, 0x8d, 0x7a, 0x61, 0xef, 0x6a, 0xf1,
	0x5f, 0xcb, 0xbf, 0x87, 0xf6, 0x0c, 0x53, 0x34, 0xf8, 0xff, 0xea, 0x57, 0x6d, 0xfa, 0xc7, 0xb8,
	0xfb, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x85, 0x94, 0xb9, 0x76, 0x40, 0x06, 0x00, 0x00,
}
