// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin.proto

package p_admin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AdminStatus int32

const (
	AdminStatus_admin_normal  AdminStatus = 0
	AdminStatus_admin_disable AdminStatus = 1
)

var AdminStatus_name = map[int32]string{
	0: "admin_normal",
	1: "admin_disable",
}

var AdminStatus_value = map[string]int32{
	"admin_normal":  0,
	"admin_disable": 1,
}

func (x AdminStatus) String() string {
	return proto.EnumName(AdminStatus_name, int32(x))
}

func (AdminStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{0}
}

//app状态
type AppStatus int32

const (
	AppStatus_app_normal   AppStatus = 0
	AppStatus_app_disabled AppStatus = 1
)

var AppStatus_name = map[int32]string{
	0: "app_normal",
	1: "app_disabled",
}

var AppStatus_value = map[string]int32{
	"app_normal":   0,
	"app_disabled": 1,
}

func (x AppStatus) String() string {
	return proto.EnumName(AppStatus_name, int32(x))
}

func (AppStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{1}
}

type Admins struct {
	Items                []*AdminInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Admins) Reset()         { *m = Admins{} }
func (m *Admins) String() string { return proto.CompactTextString(m) }
func (*Admins) ProtoMessage()    {}
func (*Admins) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{0}
}

func (m *Admins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Admins.Unmarshal(m, b)
}
func (m *Admins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Admins.Marshal(b, m, deterministic)
}
func (m *Admins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Admins.Merge(m, src)
}
func (m *Admins) XXX_Size() int {
	return xxx_messageInfo_Admins.Size(m)
}
func (m *Admins) XXX_DiscardUnknown() {
	xxx_messageInfo_Admins.DiscardUnknown(m)
}

var xxx_messageInfo_Admins proto.InternalMessageInfo

func (m *Admins) GetItems() []*AdminInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type AdminInfo struct {
	// 请求 uuid
	Id                   int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserName             string      `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPass             string      `protobuf:"bytes,4,opt,name=user_pass,json=userPass,proto3" json:"user_pass,omitempty"`
	Phone                string      `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	GroupId              int32       `protobuf:"varint,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Status               AdminStatus `protobuf:"varint,7,opt,name=status,proto3,enum=p_admin.AdminStatus" json:"status,omitempty"`
	CreateTime           string      `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	LoginTime            string      `protobuf:"bytes,9,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"`
	LoginCount           int32       `protobuf:"varint,10,opt,name=login_count,json=loginCount,proto3" json:"login_count,omitempty"`
	LoginIp              string      `protobuf:"bytes,11,opt,name=login_ip,json=loginIp,proto3" json:"login_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AdminInfo) Reset()         { *m = AdminInfo{} }
func (m *AdminInfo) String() string { return proto.CompactTextString(m) }
func (*AdminInfo) ProtoMessage()    {}
func (*AdminInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{1}
}

func (m *AdminInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminInfo.Unmarshal(m, b)
}
func (m *AdminInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminInfo.Marshal(b, m, deterministic)
}
func (m *AdminInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminInfo.Merge(m, src)
}
func (m *AdminInfo) XXX_Size() int {
	return xxx_messageInfo_AdminInfo.Size(m)
}
func (m *AdminInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AdminInfo proto.InternalMessageInfo

func (m *AdminInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdminInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdminInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AdminInfo) GetUserPass() string {
	if m != nil {
		return m.UserPass
	}
	return ""
}

func (m *AdminInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AdminInfo) GetGroupId() int32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *AdminInfo) GetStatus() AdminStatus {
	if m != nil {
		return m.Status
	}
	return AdminStatus_admin_normal
}

func (m *AdminInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *AdminInfo) GetLoginTime() string {
	if m != nil {
		return m.LoginTime
	}
	return ""
}

func (m *AdminInfo) GetLoginCount() int32 {
	if m != nil {
		return m.LoginCount
	}
	return 0
}

func (m *AdminInfo) GetLoginIp() string {
	if m != nil {
		return m.LoginIp
	}
	return ""
}

type Groups struct {
	Items                []*AdminGroup `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Groups) Reset()         { *m = Groups{} }
func (m *Groups) String() string { return proto.CompactTextString(m) }
func (*Groups) ProtoMessage()    {}
func (*Groups) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{2}
}

func (m *Groups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Groups.Unmarshal(m, b)
}
func (m *Groups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Groups.Marshal(b, m, deterministic)
}
func (m *Groups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Groups.Merge(m, src)
}
func (m *Groups) XXX_Size() int {
	return xxx_messageInfo_Groups.Size(m)
}
func (m *Groups) XXX_DiscardUnknown() {
	xxx_messageInfo_Groups.DiscardUnknown(m)
}

var xxx_messageInfo_Groups proto.InternalMessageInfo

func (m *Groups) GetItems() []*AdminGroup {
	if m != nil {
		return m.Items
	}
	return nil
}

type AdminGroup struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Menu                 []int32  `protobuf:"varint,4,rep,packed,name=menu,proto3" json:"menu,omitempty"`
	Permiss              int32    `protobuf:"varint,5,opt,name=permiss,proto3" json:"permiss,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminGroup) Reset()         { *m = AdminGroup{} }
func (m *AdminGroup) String() string { return proto.CompactTextString(m) }
func (*AdminGroup) ProtoMessage()    {}
func (*AdminGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{3}
}

func (m *AdminGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminGroup.Unmarshal(m, b)
}
func (m *AdminGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminGroup.Marshal(b, m, deterministic)
}
func (m *AdminGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminGroup.Merge(m, src)
}
func (m *AdminGroup) XXX_Size() int {
	return xxx_messageInfo_AdminGroup.Size(m)
}
func (m *AdminGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminGroup.DiscardUnknown(m)
}

var xxx_messageInfo_AdminGroup proto.InternalMessageInfo

func (m *AdminGroup) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdminGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdminGroup) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AdminGroup) GetMenu() []int32 {
	if m != nil {
		return m.Menu
	}
	return nil
}

func (m *AdminGroup) GetPermiss() int32 {
	if m != nil {
		return m.Permiss
	}
	return 0
}

type MenuMeta struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Icon                 string   `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuMeta) Reset()         { *m = MenuMeta{} }
func (m *MenuMeta) String() string { return proto.CompactTextString(m) }
func (*MenuMeta) ProtoMessage()    {}
func (*MenuMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{4}
}

func (m *MenuMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuMeta.Unmarshal(m, b)
}
func (m *MenuMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuMeta.Marshal(b, m, deterministic)
}
func (m *MenuMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuMeta.Merge(m, src)
}
func (m *MenuMeta) XXX_Size() int {
	return xxx_messageInfo_MenuMeta.Size(m)
}
func (m *MenuMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuMeta.DiscardUnknown(m)
}

var xxx_messageInfo_MenuMeta proto.InternalMessageInfo

func (m *MenuMeta) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MenuMeta) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

type Menu struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                 string    `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Redirect             string    `protobuf:"bytes,3,opt,name=redirect,proto3" json:"redirect,omitempty"`
	Name                 string    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Component            string    `protobuf:"bytes,5,opt,name=component,proto3" json:"component,omitempty"`
	Meta                 *MenuMeta `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	Label                string    `protobuf:"bytes,7,opt,name=label,proto3" json:"label,omitempty"`
	Children             []*Menu   `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`
	Parent               int32     `protobuf:"varint,9,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Menu) Reset()         { *m = Menu{} }
func (m *Menu) String() string { return proto.CompactTextString(m) }
func (*Menu) ProtoMessage()    {}
func (*Menu) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{5}
}

func (m *Menu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Menu.Unmarshal(m, b)
}
func (m *Menu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Menu.Marshal(b, m, deterministic)
}
func (m *Menu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Menu.Merge(m, src)
}
func (m *Menu) XXX_Size() int {
	return xxx_messageInfo_Menu.Size(m)
}
func (m *Menu) XXX_DiscardUnknown() {
	xxx_messageInfo_Menu.DiscardUnknown(m)
}

var xxx_messageInfo_Menu proto.InternalMessageInfo

func (m *Menu) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Menu) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Menu) GetRedirect() string {
	if m != nil {
		return m.Redirect
	}
	return ""
}

func (m *Menu) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Menu) GetComponent() string {
	if m != nil {
		return m.Component
	}
	return ""
}

func (m *Menu) GetMeta() *MenuMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Menu) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Menu) GetChildren() []*Menu {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Menu) GetParent() int32 {
	if m != nil {
		return m.Parent
	}
	return 0
}

type Menus struct {
	Items                []*Menu  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Menus) Reset()         { *m = Menus{} }
func (m *Menus) String() string { return proto.CompactTextString(m) }
func (*Menus) ProtoMessage()    {}
func (*Menus) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{6}
}

func (m *Menus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Menus.Unmarshal(m, b)
}
func (m *Menus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Menus.Marshal(b, m, deterministic)
}
func (m *Menus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Menus.Merge(m, src)
}
func (m *Menus) XXX_Size() int {
	return xxx_messageInfo_Menus.Size(m)
}
func (m *Menus) XXX_DiscardUnknown() {
	xxx_messageInfo_Menus.DiscardUnknown(m)
}

var xxx_messageInfo_Menus proto.InternalMessageInfo

func (m *Menus) GetItems() []*Menu {
	if m != nil {
		return m.Items
	}
	return nil
}

type AppInfo struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PackageName          string    `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	Platform             int32     `protobuf:"varint,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Status               AppStatus `protobuf:"varint,5,opt,name=status,proto3,enum=p_admin.AppStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AppInfo) Reset()         { *m = AppInfo{} }
func (m *AppInfo) String() string { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()    {}
func (*AppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{7}
}

func (m *AppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfo.Unmarshal(m, b)
}
func (m *AppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfo.Marshal(b, m, deterministic)
}
func (m *AppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfo.Merge(m, src)
}
func (m *AppInfo) XXX_Size() int {
	return xxx_messageInfo_AppInfo.Size(m)
}
func (m *AppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfo proto.InternalMessageInfo

func (m *AppInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AppInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppInfo) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *AppInfo) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *AppInfo) GetStatus() AppStatus {
	if m != nil {
		return m.Status
	}
	return AppStatus_app_normal
}

type AppList struct {
	Items                []*AppInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AppList) Reset()         { *m = AppList{} }
func (m *AppList) String() string { return proto.CompactTextString(m) }
func (*AppList) ProtoMessage()    {}
func (*AppList) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{8}
}

func (m *AppList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppList.Unmarshal(m, b)
}
func (m *AppList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppList.Marshal(b, m, deterministic)
}
func (m *AppList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppList.Merge(m, src)
}
func (m *AppList) XXX_Size() int {
	return xxx_messageInfo_AppList.Size(m)
}
func (m *AppList) XXX_DiscardUnknown() {
	xxx_messageInfo_AppList.DiscardUnknown(m)
}

var xxx_messageInfo_AppList proto.InternalMessageInfo

func (m *AppList) GetItems() []*AppInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type ConfigItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ConfigId             int32    `protobuf:"varint,5,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigItem) Reset()         { *m = ConfigItem{} }
func (m *ConfigItem) String() string { return proto.CompactTextString(m) }
func (*ConfigItem) ProtoMessage()    {}
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{9}
}

func (m *ConfigItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigItem.Unmarshal(m, b)
}
func (m *ConfigItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigItem.Marshal(b, m, deterministic)
}
func (m *ConfigItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigItem.Merge(m, src)
}
func (m *ConfigItem) XXX_Size() int {
	return xxx_messageInfo_ConfigItem.Size(m)
}
func (m *ConfigItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigItem.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigItem proto.InternalMessageInfo

func (m *ConfigItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ConfigItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ConfigItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ConfigItem) GetConfigId() int32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

type AppConfig struct {
	Id                   int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId                int32         `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ShowName             string        `protobuf:"bytes,3,opt,name=show_name,json=showName,proto3" json:"show_name,omitempty"`
	Configs              []*ConfigItem `protobuf:"bytes,4,rep,name=configs,proto3" json:"configs,omitempty"`
	Disclaimer           string        `protobuf:"bytes,5,opt,name=disclaimer,proto3" json:"disclaimer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AppConfig) Reset()         { *m = AppConfig{} }
func (m *AppConfig) String() string { return proto.CompactTextString(m) }
func (*AppConfig) ProtoMessage()    {}
func (*AppConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{10}
}

func (m *AppConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfig.Unmarshal(m, b)
}
func (m *AppConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfig.Marshal(b, m, deterministic)
}
func (m *AppConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfig.Merge(m, src)
}
func (m *AppConfig) XXX_Size() int {
	return xxx_messageInfo_AppConfig.Size(m)
}
func (m *AppConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfig proto.InternalMessageInfo

func (m *AppConfig) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AppConfig) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *AppConfig) GetShowName() string {
	if m != nil {
		return m.ShowName
	}
	return ""
}

func (m *AppConfig) GetConfigs() []*ConfigItem {
	if m != nil {
		return m.Configs
	}
	return nil
}

func (m *AppConfig) GetDisclaimer() string {
	if m != nil {
		return m.Disclaimer
	}
	return ""
}

type AppConfigList struct {
	Items                []*AppConfig `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AppConfigList) Reset()         { *m = AppConfigList{} }
func (m *AppConfigList) String() string { return proto.CompactTextString(m) }
func (*AppConfigList) ProtoMessage()    {}
func (*AppConfigList) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{11}
}

func (m *AppConfigList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfigList.Unmarshal(m, b)
}
func (m *AppConfigList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfigList.Marshal(b, m, deterministic)
}
func (m *AppConfigList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfigList.Merge(m, src)
}
func (m *AppConfigList) XXX_Size() int {
	return xxx_messageInfo_AppConfigList.Size(m)
}
func (m *AppConfigList) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfigList.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfigList proto.InternalMessageInfo

func (m *AppConfigList) GetItems() []*AppConfig {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterEnum("p_admin.AdminStatus", AdminStatus_name, AdminStatus_value)
	proto.RegisterEnum("p_admin.AppStatus", AppStatus_name, AppStatus_value)
	proto.RegisterType((*Admins)(nil), "p_admin.Admins")
	proto.RegisterType((*AdminInfo)(nil), "p_admin.AdminInfo")
	proto.RegisterType((*Groups)(nil), "p_admin.Groups")
	proto.RegisterType((*AdminGroup)(nil), "p_admin.AdminGroup")
	proto.RegisterType((*MenuMeta)(nil), "p_admin.MenuMeta")
	proto.RegisterType((*Menu)(nil), "p_admin.Menu")
	proto.RegisterType((*Menus)(nil), "p_admin.Menus")
	proto.RegisterType((*AppInfo)(nil), "p_admin.AppInfo")
	proto.RegisterType((*AppList)(nil), "p_admin.AppList")
	proto.RegisterType((*ConfigItem)(nil), "p_admin.ConfigItem")
	proto.RegisterType((*AppConfig)(nil), "p_admin.AppConfig")
	proto.RegisterType((*AppConfigList)(nil), "p_admin.AppConfigList")
}

func init() { proto.RegisterFile("admin.proto", fileDescriptor_73a7fc70dcc2027c) }

var fileDescriptor_73a7fc70dcc2027c = []byte{
	// 722 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x25, 0xbb, 0x9b, 0x4d, 0x32, 0x69, 0xab, 0xad, 0x29, 0x28, 0xb4, 0x40, 0x97, 0x20, 0xd0,
	0xb6, 0x6a, 0x2b, 0xb1, 0xe5, 0xc2, 0xb1, 0xea, 0x01, 0xad, 0x44, 0x11, 0x0a, 0xdc, 0x57, 0x6e,
	0xe2, 0xee, 0x5a, 0xcd, 0x87, 0x15, 0x3b, 0x45, 0xfc, 0x13, 0x4e, 0xfc, 0x1a, 0x7e, 0x14, 0x47,
	0xe4, 0x71, 0x92, 0x4d, 0xf8, 0x90, 0x7a, 0xf3, 0xbc, 0xf7, 0x62, 0xcf, 0x3c, 0x7b, 0x26, 0xe0,
	0xd3, 0x24, 0xe3, 0xf9, 0x99, 0x28, 0x0b, 0x55, 0x10, 0x47, 0x2c, 0x31, 0x0c, 0xe7, 0x30, 0xbe,
	0xd0, 0x0b, 0x49, 0x66, 0x60, 0x73, 0xc5, 0x32, 0x19, 0x58, 0xd3, 0xe1, 0xcc, 0x9f, 0x93, 0xb3,
	0x5a, 0x72, 0x86, 0xfc, 0x22, 0xbf, 0x29, 0x22, 0x23, 0x08, 0x7f, 0x0e, 0xc0, 0x6b, 0x41, 0xb2,
	0x03, 0x03, 0x9e, 0x04, 0xd6, 0xd4, 0x9a, 0xd9, 0xd1, 0x80, 0x27, 0x84, 0xc0, 0x28, 0xa7, 0x19,
	0x0b, 0x06, 0x53, 0x6b, 0xe6, 0x45, 0xb8, 0x26, 0x07, 0xe0, 0x55, 0x92, 0x95, 0x4b, 0x24, 0x86,
	0x48, 0xb8, 0x1a, 0xf8, 0xd8, 0x25, 0x05, 0x95, 0x32, 0x18, 0x6d, 0xc8, 0x4f, 0x54, 0x4a, 0xb2,
	0x07, 0xb6, 0x58, 0x17, 0x39, 0x0b, 0x6c, 0x24, 0x4c, 0x40, 0x9e, 0x80, 0xbb, 0x2a, 0x8b, 0x4a,
	0x2c, 0x79, 0x12, 0x8c, 0xf1, 0x64, 0x07, 0xe3, 0x45, 0x42, 0x4e, 0x60, 0x2c, 0x15, 0x55, 0x95,
	0x0c, 0x9c, 0xa9, 0x35, 0xdb, 0x99, 0xef, 0xf5, 0xeb, 0xf8, 0x8c, 0x5c, 0x54, 0x6b, 0xc8, 0x21,
	0xf8, 0x71, 0xc9, 0xa8, 0x62, 0x4b, 0xc5, 0x33, 0x16, 0xb8, 0x78, 0x08, 0x18, 0xe8, 0x0b, 0xcf,
	0x18, 0x79, 0x06, 0x90, 0x16, 0x2b, 0x9e, 0x1b, 0xde, 0x43, 0xde, 0x43, 0x04, 0xe9, 0x43, 0xf0,
	0x0d, 0x1d, 0x17, 0x55, 0xae, 0x02, 0xc0, 0x5c, 0xcc, 0x17, 0x97, 0x1a, 0xd1, 0x99, 0x1a, 0x01,
	0x17, 0x81, 0x8f, 0x5f, 0x3b, 0x18, 0x2f, 0x44, 0x78, 0x0e, 0xe3, 0xf7, 0x3a, 0x69, 0x49, 0x8e,
	0xfa, 0xd6, 0x3f, 0xec, 0xa7, 0x8c, 0xa2, 0xc6, 0xfb, 0x3b, 0x80, 0x0d, 0x78, 0x2f, 0xef, 0x1f,
	0xb7, 0x86, 0x0c, 0x51, 0xd7, 0x94, 0x4e, 0x60, 0x94, 0xb1, 0xbc, 0x0a, 0x46, 0xd3, 0xe1, 0xcc,
	0x8e, 0x70, 0x4d, 0x02, 0x70, 0x04, 0x2b, 0x33, 0x2e, 0x25, 0xfa, 0x6d, 0x47, 0x4d, 0x18, 0xbe,
	0x05, 0xf7, 0x8a, 0xe5, 0xd5, 0x15, 0x53, 0x54, 0xdf, 0x89, 0xe2, 0x2a, 0x65, 0x78, 0xb0, 0x17,
	0x99, 0x40, 0xef, 0xc7, 0xe3, 0x22, 0x6f, 0xce, 0xd6, 0xeb, 0xf0, 0x97, 0x05, 0x23, 0xfd, 0xd9,
	0xbf, 0x12, 0x15, 0x54, 0xad, 0x1b, 0xb1, 0x5e, 0x93, 0x7d, 0x70, 0x4b, 0x96, 0xf0, 0x92, 0xc5,
	0xaa, 0x79, 0x23, 0x4d, 0xdc, 0x16, 0x36, 0xea, 0x14, 0xf6, 0x14, 0xbc, 0xb8, 0xc8, 0x44, 0x91,
	0xb3, 0x5c, 0xd5, 0xcf, 0x63, 0x03, 0x90, 0x57, 0xba, 0x3c, 0x45, 0xf1, 0x79, 0xf8, 0xf3, 0xdd,
	0xd6, 0xd2, 0xa6, 0x8a, 0x08, 0x69, 0x5d, 0x4b, 0x4a, 0xaf, 0x59, 0x8a, 0xaf, 0xc5, 0x8b, 0x4c,
	0x40, 0x8e, 0xc0, 0x8d, 0xd7, 0x3c, 0x4d, 0x4a, 0x96, 0x07, 0x2e, 0xde, 0xc9, 0x76, 0x6f, 0x83,
	0xa8, 0xa5, 0xb5, 0xbd, 0x82, 0x96, 0x3a, 0x05, 0xcf, 0xd8, 0x6b, 0xa2, 0xf0, 0x04, 0x6c, 0xad,
	0x94, 0xe4, 0x65, 0xff, 0x72, 0xff, 0xd8, 0xa8, 0xbe, 0xd6, 0xef, 0x16, 0x38, 0x17, 0x42, 0xdc,
	0xbb, 0xa1, 0x5e, 0xc0, 0x96, 0xa0, 0xf1, 0x2d, 0x5d, 0xb1, 0x6e, 0x4f, 0xf9, 0x35, 0x86, 0x6d,
	0xb5, 0x0f, 0xae, 0x48, 0xa9, 0xba, 0x29, 0xca, 0x0c, 0x6d, 0xb3, 0xa3, 0x36, 0x26, 0xc7, 0xed,
	0x9b, 0xb0, 0xb1, 0x49, 0x3a, 0xcd, 0x2e, 0x44, 0xbf, 0x45, 0xc2, 0x37, 0x98, 0xd9, 0x07, 0x2e,
	0x15, 0x79, 0xdd, 0x2f, 0x65, 0xd2, 0xfd, 0xaa, 0x3b, 0x20, 0x2a, 0x80, 0xcb, 0x22, 0xbf, 0xe1,
	0xab, 0x85, 0x62, 0xd9, 0xbd, 0xea, 0x99, 0xc0, 0xf0, 0x96, 0x7d, 0xab, 0xcb, 0xd0, 0x4b, 0x7d,
	0x31, 0x77, 0x34, 0xad, 0x9a, 0x2b, 0x37, 0x81, 0x9e, 0x15, 0x31, 0xee, 0xac, 0x3b, 0xdf, 0x3c,
	0x51, 0xd7, 0x00, 0x8b, 0x24, 0xfc, 0x61, 0x81, 0x77, 0x21, 0x84, 0x39, 0xfa, 0xaf, 0x63, 0x1f,
	0xc1, 0x98, 0x0a, 0x9c, 0x18, 0x03, 0xc4, 0x6c, 0x2a, 0xf4, 0xbc, 0x38, 0x00, 0x4f, 0xae, 0x8b,
	0xaf, 0xbd, 0xd1, 0xa4, 0x01, 0xf4, 0xf0, 0x14, 0x1c, 0xb3, 0xbb, 0xc4, 0x36, 0xe9, 0xb6, 0xe6,
	0xa6, 0xc0, 0xa8, 0xd1, 0x90, 0xe7, 0x00, 0x09, 0x97, 0x71, 0x4a, 0x79, 0xc6, 0xca, 0xfa, 0x49,
	0x76, 0x90, 0xf0, 0x1d, 0x6c, 0xb7, 0xf9, 0xa1, 0xa1, 0xff, 0x9f, 0xb9, 0x8d, 0xac, 0xb6, 0xf4,
	0x78, 0x0e, 0x7e, 0x67, 0x7e, 0x91, 0x09, 0x6c, 0xa1, 0x70, 0x99, 0x17, 0x65, 0x46, 0xd3, 0xc9,
	0x03, 0xb2, 0x0b, 0xdb, 0x06, 0x49, 0xb8, 0xa4, 0xd7, 0x29, 0x9b, 0x58, 0xc7, 0xa7, 0x68, 0x47,
	0xfd, 0xc5, 0x0e, 0x80, 0x2e, 0xbf, 0xd5, 0xeb, 0x1d, 0x84, 0x68, 0xd4, 0xc9, 0xc4, 0xba, 0x1e,
	0xe3, 0xaf, 0xe1, 0xfc, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x91, 0x86, 0x2a, 0x29, 0x06,
	0x00, 0x00,
}
